export const cards = [
  {
    name: "3-Hump Lacooda",
    attack: 500,
    attribute: "EARTH",
    defense: 1500,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 86988864,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {\"Pharaoh's Inheritance\": {'Japanese': {'set_number': '309-015', 'rarities': ['Common'], 'date': '2004-02-26'}}, 'Ancient Sanctuary': {'Asian-English': {'set_number': 'AST-AE070', 'rarities': ['Common'], 'date': '2004-10-08'}, 'Korean': {'set_number': 'AST-KR070', 'rarities': ['Common'], 'date': '2005-08-27'}}, 'Expert Edition Volume.2': {'Japanese': {'set_number': 'EE2-JP183', 'rarities': ['Common'], 'date': '2005-03-17'}, 'Korean': {'set_number': 'HGP2-KR183', 'rarities': ['Common'], 'date': '2006-11-17'}}}, 'TCG': {'Ancient Sanctuary': {'German': {'set_number': 'AST-DE070', 'rarities': ['Common'], 'date': '2004-05-01'}, 'English (na)': {'set_number': 'AST-070', 'rarities': ['Common'], 'date': '2004-06-01'}, 'French': {'set_number': 'AST-FR070', 'rarities': ['Common'], 'date': '2004-06-01'}, 'Italian': {'set_number': 'AST-IT070', 'rarities': ['Common'], 'date': '2004-06-01'}, 'Spanish': {'set_number': 'AST-SP070', 'rarities': ['Common'], 'date': '2004-06-01'}}, 'Dark Revelation Volume 2': {'German': {'set_number': 'DR2-DE183', 'rarities': ['Common'], 'date': '2005-10-01'}, 'English (world)': {'set_number': 'DR2-EN183', 'rarities': ['Common'], 'date': '2005-10-20'}, 'French': {'set_number': 'DR2-FR183', 'rarities': ['Common'], 'date': '2005-10-20'}, 'Italian': {'set_number': 'DR2-IT183', 'rarities': ['Common'], 'date': '2005-10-20'}, 'Spanish': {'set_number': 'DR2-SP183', 'rarities': ['Common'], 'date': '2005-10-20'}}}}",
    Type: "Beast",
    stars: 3,
    text:
      'If there are 3 face-up "3-Hump Lacooda" cards on your side of the field, Tribute 2 of them to draw 3 cards.'
  },
  {
    name: "30,000-Year White Turtle",
    attack: 1250,
    attribute: "WATER",
    defense: 2100,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Normal']",
    name_condition: "",
    number: 11714098,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Booster 5': {'Japanese': {'set_number': 'Unknown', 'rarities': ['Common'], 'date': '1999-10-17'}}}}",
    Type: "Aqua",
    stars: 5,
    text: "A huge turtle that has existed for more than 30,000 years."
  },
  {
    name: "4-Starred Ladybug of Doom",
    attack: 800,
    attribute: "WIND",
    defense: 1200,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Flip', 'Effect']",
    name_condition: "",
    number: 83994646,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Thousand Eyes Bible': {'Japanese': {'set_number': 'TB-38', 'rarities': ['Common'], 'date': '2000-12-14'}}, 'Duelist Legacy Volume.3': {'Japanese': {'set_number': 'DL3-033', 'rarities': ['Common'], 'date': '2002-12-12'}}, \"Pharaoh's Servant\": {'Korean': {'set_number': 'PSV-K088', 'rarities': ['Common'], 'date': '2004-06-19'}}, \"Beginner's Edition 1\": {'Japanese': {'set_number': 'BE1-JP198', 'rarities': ['Common'], 'date': '2004-06-24'}, 'Korean': {'set_number': 'BP1-KR198', 'rarities': ['Unknown'], 'date': '2006-04-11'}}, \"Beginner's Edition 1 (2011)\": {'Japanese': {'set_number': 'BE01-JP169', 'rarities': ['Common'], 'date': '2011-05-14'}}, 'Starter Pack Volume 1': {'Chinese': {'set_number': 'SP01-TC021', 'rarities': ['Common'], 'date': '2014-03-01'}}}, 'TCG': {\"Pharaoh's Servant\": {'English (na)': {'set_number': 'PSV-088', 'rarities': ['Common'], 'date': '2002-10-20'}, 'English (world)': {'set_number': 'PSV-EN088', 'rarities': ['Common'], 'date': '2004-12-01'}}, 'Dark Beginning 1': {'English (na)': {'set_number': 'DB1-EN198', 'rarities': ['Common'], 'date': '2004-10-12'}, 'Spanish': {'set_number': 'DB1-SP198', 'rarities': ['Common'], 'date': '2004-12-01'}, 'German': {'set_number': 'DB1-DE198', 'rarities': ['Common'], 'date': '2004-12-17'}}, 'Retro Pack 2': {'French': {'set_number': 'RP02-FR022', 'rarities': ['Common'], 'date': '2009-07-23'}, 'Italian': {'set_number': 'RP02-IT022', 'rarities': ['Common'], 'date': '2009-07-23'}, 'Spanish': {'set_number': 'RP02-SP022', 'rarities': ['Common'], 'date': '2009-07-23'}, 'German': {'set_number': 'RP02-DE022', 'rarities': ['Common'], 'date': '2009-07-24'}, 'English (world)': {'set_number': 'RP02-EN022', 'rarities': ['Common'], 'date': '2009-07-28'}}, 'Starter Deck: Yugi Reloaded': {'French': {'set_number': 'YSYR-FR010', 'rarities': ['Common'], 'date': '2013-12-05'}, 'German': {'set_number': 'YSYR-DE010', 'rarities': ['Common'], 'date': '2013-12-05'}, 'Italian': {'set_number': 'YSYR-IT010', 'rarities': ['Common'], 'date': '2013-12-05'}, 'Spanish': {'set_number': 'YSYR-SP010', 'rarities': ['Common'], 'date': '2013-12-05'}, 'English (eu)': {'set_number': 'YSYR-EN010', 'rarities': ['Common'], 'date': '2013-12-06'}, 'English (na)': {'set_number': 'YSYR-EN010', 'rarities': ['Common'], 'date': '2013-12-06'}, 'English (oc)': {'set_number': 'YSYR-EN010', 'rarities': ['Common'], 'date': '2013-12-06'}, 'Portuguese': {'set_number': 'YSYR-PT010', 'rarities': ['Common'], 'date': '2013-12-06'}, 'Spanish (lat-am)': {'set_number': 'YSYR-SP010', 'rarities': ['Common'], 'date': '2013-12-06'}}}}",
    Type: "Insect",
    stars: 3,
    text: "FLIP: Destroy all Level 4 monsters your opponent controls."
  },
  {
    name: "7 Colored Fish",
    attack: 1800,
    attribute: "WATER",
    defense: 800,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Normal']",
    name_condition: "",
    number: 23771716,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Vol.7': {'Japanese': {'set_number': 'Unknown', 'rarities': ['Common'], 'date': '2000-01-27'}}, 'Metal Raiders': {'Japanese': {'set_number': 'ME-38', 'rarities': ['Common'], 'date': '2001-02-22'}, 'Korean': {'set_number': 'MRD-K098', 'rarities': ['Common'], 'date': '2004-03-09'}}, 'Duelist Legacy Volume.4': {'Japanese': {'set_number': 'DL4-032', 'rarities': ['Common'], 'date': '2003-01-23'}}, 'Starter Deck: Joey': {'Korean': {'set_number': 'SDJ-KR008', 'rarities': ['Common'], 'date': '2004-08-16'}}, 'Structure Deck: Fury from the Deep': {'Japanese': {'set_number': 'SD4-JP002', 'rarities': ['Common'], 'date': '2005-01-20'}, 'Korean': {'set_number': 'SD4-KR002', 'rarities': ['Common'], 'date': '2006-04-29'}}, 'Starter Pack Volume 2': {'Chinese': {'set_number': 'SP02-TC003', 'rarities': ['Common'], 'date': '2014-09-27'}}}, 'TCG': {'Metal Raiders': {'English (na)': {'set_number': 'MRD-098', 'rarities': ['Common'], 'date': '2002-06-26'}, 'French': {'set_number': 'MRD-F098', 'rarities': ['Common'], 'date': '2002-06-27'}, 'German': {'set_number': 'MRD-G098', 'rarities': ['Common'], 'date': '2002-06-27'}, 'Spanish': {'set_number': 'PMT-S098', 'rarities': ['Common'], 'date': '2002-06-27'}, 'English (eu)': {'set_number': 'MRD-E098', 'rarities': ['Common'], 'date': '2003-07-23'}, 'Italian': {'set_number': 'PMT-I098', 'rarities': ['Common'], 'date': '2003-08-07'}, 'English (world)': {'set_number': 'MRD-EN098', 'rarities': ['Common'], 'date': '2004-12-01'}}, 'Starter Deck: Joey': {'English (na)': {'set_number': 'SDJ-008', 'rarities': ['Common'], 'date': '2003-03-30'}, 'French': {'set_number': 'DDJ-F008', 'rarities': ['Common'], 'date': '2003-03-30'}, 'German': {'set_number': 'SDJ-G008', 'rarities': ['Common'], 'date': '2003-03-30'}, 'Italian': {'set_number': 'MIJ-I008', 'rarities': ['Common'], 'date': '2003-03-30'}, 'Spanish': {'set_number': 'BIJ-S008', 'rarities': ['Common'], 'date': '2003-03-30'}}, 'Structure Deck: Fury from the Deep': {'English (na)': {'set_number': 'SD4-EN002', 'rarities': ['Common'], 'date': '2005-05-09'}, 'French': {'set_number': 'SD4-FR002', 'rarities': ['Common'], 'date': '2005-05-09'}, 'German': {'set_number': 'SD4-DE002', 'rarities': ['Common'], 'date': '2005-05-09'}, 'Italian': {'set_number': 'SD4-IT002', 'rarities': ['Common'], 'date': '2005-05-09'}, 'Spanish': {'set_number': 'SD4-SP002', 'rarities': ['Common'], 'date': '2005-05-09'}}, 'Gold Series': {'English (na)': {'set_number': 'GLD1-EN001', 'rarities': ['Common'], 'date': '2008-04-02'}, 'English (eu)': {'set_number': 'GLD1-EN001', 'rarities': ['Common'], 'date': '2008-04-09'}, 'French': {'set_number': 'GLD1-FR001', 'rarities': ['Common'], 'date': '2008-04-09'}, 'German': {'set_number': 'GLD1-DE001', 'rarities': ['Common'], 'date': '2008-04-09'}, 'Italian': {'set_number': 'GLD1-IT001', 'rarities': ['Common'], 'date': '2008-04-09'}, 'Spanish': {'set_number': 'GLD1-SP001', 'rarities': ['Common'], 'date': '2008-04-09'}}}}",
    Type: "Fish",
    stars: 4,
    text: "A rare rainbow fish that has never been caught by mortal man."
  },
  {
    name: "8-Claws Scorpion",
    attack: 300,
    attribute: "DARK",
    defense: 200,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 14261867,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Duelist Legacy Volume.5': {'Japanese': {'set_number': 'DL5-109', 'rarities': ['Common'], 'date': '2003-04-24'}}, 'Pharaonic Guardian': {'Asian-English': {'set_number': 'PGD-024', 'rarities': ['Common'], 'date': '2003-10-16'}, 'Korean': {'set_number': 'PGD-KR024', 'rarities': ['Common'], 'date': '2004-12-14'}}}, 'TCG': {'Pharaonic Guardian': {'English (na)': {'set_number': 'PGD-024', 'rarities': ['Common'], 'date': '2003-07-18'}}, 'Gold Series': {'English (na)': {'set_number': 'GLD1-EN007', 'rarities': ['Common'], 'date': '2008-04-02'}, 'English (eu)': {'set_number': 'GLD1-EN007', 'rarities': ['Common'], 'date': '2008-04-09'}, 'French': {'set_number': 'GLD1-FR007', 'rarities': ['Common'], 'date': '2008-04-09'}, 'German': {'set_number': 'GLD1-DE007', 'rarities': ['Common'], 'date': '2008-04-09'}, 'Italian': {'set_number': 'GLD1-IT007', 'rarities': ['Common'], 'date': '2008-04-09'}, 'Spanish': {'set_number': 'GLD1-SP007', 'rarities': ['Common'], 'date': '2008-04-09'}}}}",
    Type: "Insect",
    stars: 2,
    text:
      "Once per turn, you can flip this card into face-down Defense Position. When this card attacks an opponent's face-down Defense Position monster, this card's ATK becomes 2400 during damage calculation only."
  },
  {
    name: "A Cat of Ill Omen",
    attack: 500,
    attribute: "DARK",
    defense: 300,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 24140059,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'The New Ruler': {'Japanese': {'set_number': '301-018', 'rarities': ['Common'], 'date': '2002-05-16'}}, 'Pharaonic Guardian': {'Asian-English': {'set_number': 'PGD-070', 'rarities': ['Common'], 'date': '2003-10-16'}, 'Korean': {'set_number': 'PGD-KR070', 'rarities': ['Common'], 'date': '2004-12-14'}}, 'Structure Deck: Marik': {'Japanese': {'set_number': 'SDM-011', 'rarities': ['Common'], 'date': '2004-03-25'}}, 'Expert Edition Volume.1': {'Japanese': {'set_number': 'EE1-JP018', 'rarities': ['Common'], 'date': '2004-09-23'}, 'Korean': {'set_number': 'HGP1-KR018', 'rarities': ['Common'], 'date': '2006-07-06'}}, 'Advanced Tournament Pack 2015 Vol.2': {'Japanese': {'set_number': 'AT10-JP005', 'rarities': ['Common'], 'date': '2015-05-01'}}, 'Advanced Event Pack 2015 Vol.2': {'Korean': {'set_number': 'AE08-KR005', 'rarities': ['Common'], 'date': '2015-08-22'}}}, 'TCG': {'Pharaonic Guardian': {'English (na)': {'set_number': 'PGD-070', 'rarities': ['Common'], 'date': '2003-07-18'}}, 'Dark Revelation Volume 1': {'English (na)': {'set_number': 'DR1-EN018', 'rarities': ['Common'], 'date': '2005-03-19'}, 'French': {'set_number': 'DR1-FR018', 'rarities': ['Common'], 'date': '2005-03-19'}, 'Italian': {'set_number': 'DR1-IT018', 'rarities': ['Common'], 'date': '2005-03-19'}, 'Spanish': {'set_number': 'DR1-SP018', 'rarities': ['Common'], 'date': '2005-03-19'}, 'German': {'set_number': 'DR1-DE018', 'rarities': ['Common'], 'date': '2005-06-01'}}}}",
    Type: "Beast",
    stars: 2,
    text:
      'FLIP: Select 1 Trap Card from your Deck and place it on top of your Deck. If "Necrovalley" is on the field, you can add the selected card to your hand instead.'
  },
  {
    name: "A Man with Wdjat",
    attack: 1600,
    attribute: "DARK",
    defense: 1600,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 51351302,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'The New Ruler': {'Japanese': {'set_number': '301-016', 'rarities': ['Common'], 'date': '2002-05-16'}}, 'Pharaonic Guardian': {'Asian-English': {'set_number': 'PGD-068', 'rarities': ['Common'], 'date': '2003-10-16'}, 'Korean': {'set_number': 'PGD-KR068', 'rarities': ['Common'], 'date': '2004-12-14'}}, 'Expert Edition Volume.1': {'Japanese': {'set_number': 'EE1-JP016', 'rarities': ['Common'], 'date': '2004-09-23'}, 'Korean': {'set_number': 'HGP1-KR016', 'rarities': ['Common'], 'date': '2006-07-06'}}}, 'TCG': {'Pharaonic Guardian': {'English (na)': {'set_number': 'PGD-068', 'rarities': ['Common'], 'date': '2003-07-18'}}, 'Dark Revelation Volume 1': {'English (na)': {'set_number': 'DR1-EN016', 'rarities': ['Common'], 'date': '2005-03-19'}, 'French': {'set_number': 'DR1-FR016', 'rarities': ['Common'], 'date': '2005-03-19'}, 'Italian': {'set_number': 'DR1-IT016', 'rarities': ['Common'], 'date': '2005-03-19'}, 'Spanish': {'set_number': 'DR1-SP016', 'rarities': ['Common'], 'date': '2005-03-19'}, 'German': {'set_number': 'DR1-DE016', 'rarities': ['Common'], 'date': '2005-06-01'}}}}",
    Type: "Spellcaster",
    stars: 4,
    text:
      "When you Normal Summon this card, and during each of your Standby Phases, select 1 Set card on your opponent's side of the field. Pick it up and look at it, then return it to its original position."
  },
  {
    name: "A-Assault Core",
    attack: 1900,
    attribute: "LIGHT",
    defense: 200,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Union', 'Effect']",
    name_condition: "",
    number: 30012506,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Structure Deck: Seto Kaiba': {'English (eu)': {'set_number': 'SDKS-EN001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'English (oc)': {'set_number': 'SDKS-EN001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'French': {'set_number': 'SDKS-FR001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'German': {'set_number': 'SDKS-DE001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'Italian': {'set_number': 'SDKS-IT001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'Spanish': {'set_number': 'SDKS-SP001', 'rarities': ['Super Rare'], 'date': '2016-10-20'}, 'English (na)': {'set_number': 'SDKS-EN001', 'rarities': ['Super Rare'], 'date': '2016-10-21'}, 'Portuguese': {'set_number': 'SDKS-PT001', 'rarities': ['Super Rare'], 'date': '2016-10-21'}, 'Spanish (lat-am)': {'set_number': 'SDKS-SP001', 'rarities': ['Super Rare'], 'date': '2016-10-21'}}}, 'OCG': {'Structure Deck: Seto Kaiba': {'Japanese': {'set_number': 'SDKS-JP001', 'rarities': ['Super Rare'], 'date': '2016-06-18'}, 'Korean': {'set_number': 'SDKS-KR001', 'rarities': ['Super Rare'], 'date': '2016-10-07'}}}}",
    Type: "Machine",
    stars: 4,
    text:
      "Once per turn, you can either: Target 1 LIGHT Machine-Type monster you control; equip this card to that target, OR: Unequip this card and Special Summon it. A monster equipped with this card is unaffected by your opponent's monster effects (except its own), also if the equipped monster would be destroyed by battle or card effect, destroy this card instead. If this card is sent from the field to the Graveyard: You can add 1 other Union monster from your Graveyard to your hand."
  },
  {
    name: "A-Team: Trap Disposal Unit",
    attack: 300,
    attribute: "FIRE",
    defense: 400,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 13026402,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Rise of Destiny': {'Japanese': {'set_number': 'RDS-JP033', 'rarities': ['Rare'], 'date': '2004-08-05'}, 'Korean': {'set_number': 'RDS-KR033', 'rarities': ['Rare'], 'date': '2006-02-07'}}, 'Expert Edition Volume.3': {'Japanese': {'set_number': 'EE3-JP093', 'rarities': ['Rare'], 'date': '2005-12-08'}, 'Korean': {'set_number': 'HGP3-KR093', 'rarities': ['Rare'], 'date': '2008-07-05'}}}, 'TCG': {'Rise of Destiny': {'French': {'set_number': 'RDS-FR033', 'rarities': ['Rare', 'Ultimate Rare'], 'date': '2004-11-01'}, 'Spanish': {'set_number': 'RDS-SP033', 'rarities': ['Rare', 'Ultimate Rare'], 'date': '2004-11-01'}, 'English (na)': {'set_number': 'RDS-EN033', 'rarities': ['Rare', 'Ultimate Rare'], 'date': '2004-12-01'}, 'German': {'set_number': 'RDS-DE033', 'rarities': ['Rare', 'Ultimate Rare'], 'date': '2004-12-01'}, 'Italian': {'set_number': 'RDS-IT033', 'rarities': ['Rare', 'Ultimate Rare'], 'date': '2004-12-01'}}, 'Dark Revelation Volume 3': {'English (world)': {'set_number': 'DR3-EN093', 'rarities': ['Rare'], 'date': '2006-11-25'}, 'French': {'set_number': 'DR3-FR093', 'rarities': ['Rare'], 'date': '2006-11-25'}, 'German': {'set_number': 'DR3-DE093', 'rarities': ['Rare'], 'date': '2006-11-25'}, 'Italian': {'set_number': 'DR3-IT093', 'rarities': ['Rare'], 'date': '2006-11-25'}, 'Spanish': {'set_number': 'DR3-SP093', 'rarities': ['Rare'], 'date': '2006-11-25'}}}}",
    Type: "Machine",
    stars: 2,
    text:
      "This effect can be used during either player's turn. When your opponent activates a Trap Card, Tribute this face-up card to negate the activation of the Trap Card and destroy it."
  },
  {
    name: "A-to-Z-Dragon Buster Cannon",
    attack: 4000,
    attribute: "LIGHT",
    defense: 4000,
    has_materials: "True",
    has_name_condition: "False",
    is_extra_deck: "True",
    is_fusion: "True",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: 'ABC-Dragon Buster" + "XYZ-Dragon Cannon',
    monster_types: "['Fusion', 'Effect']",
    name_condition: "",
    number: 65172015,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Structure Deck: Seto Kaiba': {'English (eu)': {'set_number': 'SDKS-EN040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'English (oc)': {'set_number': 'SDKS-EN040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'French': {'set_number': 'SDKS-FR040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'German': {'set_number': 'SDKS-DE040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'Italian': {'set_number': 'SDKS-IT040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'Spanish': {'set_number': 'SDKS-SP040', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'English (na)': {'set_number': 'SDKS-EN040', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}, 'Portuguese': {'set_number': 'SDKS-PT040', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}, 'Spanish (lat-am)': {'set_number': 'SDKS-SP040', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}}}, 'OCG': {'Structure Deck: Seto Kaiba': {'Japanese': {'set_number': 'SDKS-JP040', 'rarities': ['Ultra Rare'], 'date': '2016-06-18'}, 'Korean': {'set_number': 'SDKS-KR040', 'rarities': ['Ultra Rare'], 'date': '2016-10-07'}}}}",
    Type: "Machine",
    stars: 10,
    text:
      'Must be Special Summoned (from your Extra Deck) by banishing cards you control with the above original names, and cannot be Special Summoned by other ways. (You do not use "Polymerization".) During either player\'s turn, when your opponent activates a Spell/Trap Card, or monster effect: You can discard 1 card; negate the activation, and if you do, destroy that card. During either player\'s turn: You can banish this card, then target 1 each of your banished "ABC-Dragon Buster", and "XYZ-Dragon Cannon"; Special Summon them.'
  },
  {
    name: "A/D Changer",
    attack: 100,
    attribute: "LIGHT",
    defense: 100,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 96146814,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Duelist Revolution': {'French': {'set_number': 'DREV-FR005', 'rarities': ['Common'], 'date': '2010-08-12'}, 'German': {'set_number': 'DREV-DE005', 'rarities': ['Common'], 'date': '2010-08-12'}, 'Italian': {'set_number': 'DREV-IT005', 'rarities': ['Common'], 'date': '2010-08-12'}, 'Spanish': {'set_number': 'DREV-SP005', 'rarities': ['Common'], 'date': '2010-08-12'}, 'English (na)': {'set_number': 'DREV-EN005', 'rarities': ['Common'], 'date': '2010-08-17'}}, 'Duelist Pack: Yusei 3': {'French': {'set_number': 'DP10-FR010', 'rarities': ['Common'], 'date': '2011-01-20'}, 'German': {'set_number': 'DP10-DE010', 'rarities': ['Common'], 'date': '2011-01-20'}, 'Italian': {'set_number': 'DP10-IT010', 'rarities': ['Common'], 'date': '2011-01-20'}, 'Spanish': {'set_number': 'DP10-SP010', 'rarities': ['Common'], 'date': '2011-01-20'}, 'English (eu)': {'set_number': 'DP10-EN010', 'rarities': ['Common'], 'date': '2011-01-21'}, 'English (oc)': {'set_number': 'DP10-EN010', 'rarities': ['Common'], 'date': '2011-01-21'}, 'English (na)': {'set_number': 'DP10-EN010', 'rarities': ['Common'], 'date': '2011-01-25'}, 'Spanish (lat-am)': {'set_number': 'DP10-SP010', 'rarities': ['Common'], 'date': '2011-01-25'}}, 'War of the Giants Reinforcements': {'German': {'set_number': 'WGRT-DE032', 'rarities': ['Common'], 'date': '2014-01-16'}, 'Italian': {'set_number': 'WGRT-IT032', 'rarities': ['Common'], 'date': '2014-01-16'}, 'Spanish': {'set_number': 'WGRT-SP032', 'rarities': ['Common'], 'date': '2014-01-16'}, 'English (eu)': {'set_number': 'WGRT-EN032', 'rarities': ['Common'], 'date': '2014-01-17'}, 'French': {'set_number': 'WGRT-FR032', 'rarities': ['Common'], 'date': '2014-01-17'}, 'Portuguese': {'set_number': 'WGRT-PT032', 'rarities': ['Common'], 'date': '2014-01-17'}}, 'War of the Giants: Round 2': {'English (na)': {'set_number': 'BPW2-EN032', 'rarities': ['Common'], 'date': '2014-01-17'}}}, 'OCG': {'Duelist Revolution': {'Japanese': {'set_number': 'DREV-JP005', 'rarities': ['Common'], 'date': '2010-04-17'}, 'Korean': {'set_number': 'DREV-KR005', 'rarities': ['Common'], 'date': '2010-07-17'}}, 'Duelist Pack: Yusei 3': {'Japanese': {'set_number': 'DP10-JP010', 'rarities': ['Common'], 'date': '2010-10-16'}, 'Korean': {'set_number': 'DP10-KR010', 'rarities': ['Common'], 'date': '2011-03-08'}}}}",
    Type: "Warrior",
    stars: 1,
    text:
      "You can banish this card from your Graveyard, then target 1 monster on the field; change its battle position."
  },
  {
    name: "Abaki",
    attack: 1700,
    attribute: "FIRE",
    defense: 1000,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 12694768,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Cyberdark Impact': {'French': {'set_number': 'CDIP-FR013', 'rarities': ['Common'], 'date': '2006-11-04'}, 'Spanish': {'set_number': 'CDIP-SP013', 'rarities': ['Common'], 'date': '2006-11-04'}, 'English (na)': {'set_number': 'CDIP-EN013', 'rarities': ['Common'], 'date': '2006-11-15'}, 'German': {'set_number': 'CDIP-DE013', 'rarities': ['Common'], 'date': '2006-11-15'}, 'Italian': {'set_number': 'CDIP-IT013', 'rarities': ['Common'], 'date': '2006-11-24'}, 'English (world)': {'set_number': 'CDIP-EN013', 'rarities': ['Common'], 'date': 'Unknown'}}, 'Starter Deck: Syrus Truesdale': {'English (na)': {'set_number': 'YSDS-EN020', 'rarities': ['Common'], 'date': '2007-07-25'}, 'French': {'set_number': 'YSDS-FR020', 'rarities': ['Common'], 'date': '2007-07-25'}, 'German': {'set_number': 'YSDS-DE020', 'rarities': ['Common'], 'date': '2007-07-25'}, 'Italian': {'set_number': 'YSDS-IT020', 'rarities': ['Common'], 'date': '2007-07-25'}, 'Spanish': {'set_number': 'YSDS-SP020', 'rarities': ['Common'], 'date': '2007-07-25'}}}, 'OCG': {'Cyberdark Impact': {'Japanese': {'set_number': 'CDIP-JP013', 'rarities': ['Common'], 'date': '2006-08-10'}, 'Korean': {'set_number': 'CDIP-KR013', 'rarities': ['Common'], 'date': '2007-12-21'}}}}",
    Type: "Fiend",
    stars: 4,
    text:
      "When this card is destroyed and sent to the Graveyard by battle, both players take 500 damage."
  },
  {
    name: "Abare Ushioni",
    attack: 1200,
    attribute: "EARTH",
    defense: 1200,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 89718302,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Flaming Eternity': {'Japanese': {'set_number': 'FET-JP026', 'rarities': ['Common'], 'date': '2004-11-25'}, 'Korean': {'set_number': 'FET-KR026', 'rarities': ['Common'], 'date': '2006-05-19'}}, 'Expert Edition Volume.3': {'Japanese': {'set_number': 'EE3-JP146', 'rarities': ['Common'], 'date': '2005-12-08'}, 'Korean': {'set_number': 'HGP3-KR146', 'rarities': ['Common'], 'date': '2008-07-05'}}}, 'TCG': {'Flaming Eternity': {'English (na)': {'set_number': 'FET-EN026', 'rarities': ['Common'], 'date': '2005-03-01'}, 'French': {'set_number': 'FET-FR026', 'rarities': ['Common'], 'date': '2005-03-01'}, 'German': {'set_number': 'FET-DE026', 'rarities': ['Common'], 'date': '2005-03-01'}, 'Italian': {'set_number': 'FET-IT026', 'rarities': ['Common'], 'date': '2005-03-01'}, 'Spanish': {'set_number': 'FET-SP026', 'rarities': ['Common'], 'date': '2005-03-01'}}, 'Dark Revelation Volume 3': {'English (world)': {'set_number': 'DR3-EN146', 'rarities': ['Common'], 'date': '2006-11-25'}, 'French': {'set_number': 'DR3-FR146', 'rarities': ['Common'], 'date': '2006-11-25'}, 'German': {'set_number': 'DR3-DE146', 'rarities': ['Common'], 'date': '2006-11-25'}, 'Italian': {'set_number': 'DR3-IT146', 'rarities': ['Common'], 'date': '2006-11-25'}, 'Spanish': {'set_number': 'DR3-SP146', 'rarities': ['Common'], 'date': '2006-11-25'}}}}",
    Type: "Beast-Warrior",
    stars: 4,
    text:
      "Once per turn, you can toss a coin and call it. If you call it right, inflict 1000 damage to your opponent. If you call it wrong, you take 1000 damage."
  },
  {
    name: "ABC-Dragon Buster",
    attack: 3000,
    attribute: "LIGHT",
    defense: 2800,
    has_materials: "True",
    has_name_condition: "False",
    is_extra_deck: "True",
    is_fusion: "True",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: 'A-Assault Core" + "B-Buster Drake" + "C-Crush Wyvern',
    monster_types: "['Fusion', 'Effect']",
    name_condition: "",
    number: "01561110",
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Structure Deck: Seto Kaiba': {'English (eu)': {'set_number': 'SDKS-EN041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'English (oc)': {'set_number': 'SDKS-EN041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'French': {'set_number': 'SDKS-FR041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'German': {'set_number': 'SDKS-DE041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'Italian': {'set_number': 'SDKS-IT041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'Spanish': {'set_number': 'SDKS-SP041', 'rarities': ['Ultra Rare'], 'date': '2016-10-20'}, 'English (na)': {'set_number': 'SDKS-EN041', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}, 'Portuguese': {'set_number': 'SDKS-PT041', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}, 'Spanish (lat-am)': {'set_number': 'SDKS-SP041', 'rarities': ['Ultra Rare'], 'date': '2016-10-21'}}}, 'OCG': {'Structure Deck: Seto Kaiba': {'Japanese': {'set_number': 'SDKS-JP041', 'rarities': ['Ultra Rare'], 'date': '2016-06-18'}, 'Korean': {'set_number': 'SDKS-KR041', 'rarities': ['Ultra Rare'], 'date': '2016-10-07'}}}}",
    Type: "Machine",
    stars: 8,
    text:
      "Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control and/or from your Graveyard. (You do not use \"Polymerization\".) Once per turn, during either player's turn: You can discard 1 card, then target 1 card on the field; banish it. During your opponent's turn: You can Tribute this card, then target 3 of your banished LIGHT Machine-Type Union monsters with different names; Special Summon them (this is a Quick Effect)."
  },
  {
    name: "Absolute Crusader",
    attack: 1800,
    attribute: "EARTH",
    defense: 1200,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 70832512,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Generation Force': {'English (oc)': {'set_number': 'GENF-EN036', 'rarities': ['Super Rare'], 'date': '2011-08-12'}, 'English (na)': {'set_number': 'GENF-EN036', 'rarities': ['Super Rare'], 'date': '2011-08-16'}, 'Spanish (lat-am)': {'set_number': 'GENF-SP036', 'rarities': ['Super Rare'], 'date': '2011-08-16'}, 'French': {'set_number': 'GENF-FR036', 'rarities': ['Super Rare'], 'date': 'Unknown'}, 'German': {'set_number': 'GENF-DE036', 'rarities': ['Super Rare'], 'date': 'Unknown'}, 'Italian': {'set_number': 'GENF-IT036', 'rarities': ['Super Rare'], 'date': 'Unknown'}, 'Spanish': {'set_number': 'GENF-SP036', 'rarities': ['Super Rare'], 'date': 'Unknown'}}, 'Legendary Dragon Decks': {'English (na)': {'set_number': 'LEDD-ENA13', 'rarities': ['Common'], 'date': '2017-10-06'}}}, 'OCG': {'Generation Force': {'Japanese': {'set_number': 'GENF-JP036', 'rarities': ['Super Rare'], 'date': '2011-04-16'}, 'Korean': {'set_number': 'GENF-KR036', 'rarities': ['Super Rare'], 'date': '2011-09-26'}}}}",
    Type: "Warrior",
    stars: 4,
    text:
      "When a Level 5 or higher monster is Special Summoned: Tribute this face-up card on the field; destroy that Level 5 or higher monster."
  },
  {
    name: "Absolute King Back Jack",
    attack: 0,
    attribute: "DARK",
    defense: 0,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: 60990740,
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'OCG': {'Premium Pack 17': {'Japanese': {'set_number': 'PP17-JP002', 'rarities': ['Common', 'Secret Rare'], 'date': '2015-03-21'}}, 'Premium Pack Vol.10': {'Korean': {'set_number': 'PP10-KR002', 'rarities': ['Super Rare'], 'date': '2015-06-20'}}}, 'TCG': {'Premium Gold: Return of the Bling': {'English (eu)': {'set_number': 'PGL2-EN002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'English (oc)': {'set_number': 'PGL2-EN002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'French': {'set_number': 'PGL2-FR002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'German': {'set_number': 'PGL2-DE002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'Italian': {'set_number': 'PGL2-IT002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'Spanish': {'set_number': 'PGL2-SP002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-19'}, 'English (world)': {'set_number': 'PGL2-EN002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-20'}, 'Portuguese': {'set_number': 'PGL2-PT002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-20'}, 'Spanish (lat-am)': {'set_number': 'PGL2-SP002', 'rarities': ['Gold Secret Rare'], 'date': '2015-03-20'}}}}",
    Type: "Fiend",
    stars: 1,
    text:
      'During your opponent\'s turn: You can banish this card from the Graveyard (this is a Quick Effect); excavate the top card of your Deck, and if it is a Normal Trap Card, Set it to your side of the field. Otherwise, send it to the Graveyard. That Set card can be activated during this turn. If this card is sent to the Graveyard: You can look at 3 cards from the top of your Deck, then place them on the top of the Deck in any order. You can only use each effect of "Absolute King Back Jack" once per turn.'
  },
  {
    name: "Absorbing Jar",
    attack: 600,
    attribute: "EARTH",
    defense: 500,
    has_materials: "False",
    has_name_condition: "False",
    is_extra_deck: "False",
    is_fusion: "False",
    is_link: "False",
    is_pendulum: "False",
    is_synchro: "False",
    is_xyz: "False",
    link_markers: "",
    link_number: "",
    materials: "",
    monster_types: "['Effect']",
    name_condition: "",
    number: "03900605",
    pendulum_left: "",
    pendulum_right: "",
    pendulum_text: "",
    releases:
      "{'TCG': {'Galactic Overlord': {'English (na)': {'set_number': 'GAOV-EN037', 'rarities': ['Rare'], 'date': '2012-05-08'}, 'French': {'set_number': 'GAOV-FR037', 'rarities': ['Rare'], 'date': '2012-05-10'}, 'German': {'set_number': 'GAOV-DE037', 'rarities': ['Rare'], 'date': '2012-05-10'}, 'Italian': {'set_number': 'GAOV-IT037', 'rarities': ['Rare'], 'date': '2012-05-10'}, 'Spanish': {'set_number': 'GAOV-SP037', 'rarities': ['Rare'], 'date': '2012-05-10'}, 'English (eu)': {'set_number': 'GAOV-EN037', 'rarities': ['Rare'], 'date': '2012-05-11'}, 'English (oc)': {'set_number': 'GAOV-EN037', 'rarities': ['Rare'], 'date': '2012-05-11'}}}, 'OCG': {'Galactic Overlord': {'Japanese': {'set_number': 'GAOV-JP037', 'rarities': ['Rare'], 'date': '2012-02-18'}, 'Korean': {'set_number': 'GAOV-KR037', 'rarities': ['Rare'], 'date': '2012-05-21'}}}}",
    Type: "Rock",
    stars: 3,
    text:
      "FLIP: Destroy all Set Spell/Trap Cards on the field, then each player draws 1 card for each of the cards they controlled that was destroyed by this effect. You cannot Set any cards this turn."
  }
];
